# baseURL = 'https://metafunctor.com/'

baseURL = 'https://queelius.github.io/metafunctor/'
publishDir = 'docs'

languageCode = 'en-us'
title = 'metafunctor'
theme = 'ananke'

SectionPagesMenu = 'main'
googleAnalytics = ''
enableRobotsTXT = true

[markup]
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[pagination]
  pagerSize = 10

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[services]
  [services.googleAnalytics]
    ID = 'G-E08ZXTFTTY'
  [services.disqus]
    shortname = 'metafunctor-com'

[outputs]
  home = ["HTML", "JSON"]


[params]
  math = true
  author = "Alex Towell"
  email = "lex@metafunctor.com"

  [params.social]
    [[params.social.links]]
    name = "Twitter"
    url = "https://twitter.com/queelius"
    icon = "fab fa-twitter"

    [[params.social.links]]
    name = "GitHub"
    url = "https://github.com/queelius"
    icon = "fab fa-github"

    [[params.social.links]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/alexander-towell-487015151/"
    icon = "fab fa-linkedin"

    [[params.social.links]]
    name = "RSS"
    url = "/index.xml"
    icon = "fas fa-rss"

    [[params.social.links]]
    name = "Email"
    url = "mailto:lex@metafunctor.com"
    icon = "fas fa-envelope"

    [[params.social.links]]
    name = "Keybase"
    url = "https://keybase.io/queelius"
    icon = "fab fa-keybase"

    [[params.social.links]]
    name = "YouTube"
    url = "https://www.youtube.com/@queelius"
    icon = "fab fa-youtube"

    [[params.social.links]]
    name = "Google Scholar"
    url = "https://scholar.google.com/citations?view_op=list_works&hl=en&user=E9mnFzQAAAAJ"
    icon = "fas fa-graduation-cap"

    [[params.social.links]]
    name = "ORCID"
    url = "https://orcid.org/my-orcid?orcid=0000-0001-6443-9897"
    icon = "fab fa-orcid"


    [menu]

    
  [[menu.main]]
    identifier = "social"
    name = "Social"
    url = "/social/"
    weight = 100
