baseURL = 'https://metafunctor.com/'
languageCode = 'en-us'
title = 'metafunctor'
theme = 'ananke'

SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[markup]
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[pagination]
  pagerSize = 10

[params]
  math = true
  author = "Alex Towell"
  email = "lex@metafunctor.com"

  [[params.social]]
  name = "twitter"
  url = "https://twitter.com/queelius"

  [[params.social]]
  name = "github"
  url = "https://github.com/queelius"

  [[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/alexander-towell-487015151/"

  [[params.social]]
  name = "rss"
  url = "/index.xml"

  [[params.social]]
  name = "✉️"
  url = "mailto:lex@metafunctor.com"

  [[params.social]]
  name = "keybase"
  url = "https://keybase.io/queelius"

  [[params.social]]
  name = "youtube"
  url = "https://www.youtube.com/@queelius"

  [[params.social]]
  name = "💬"
  url = "https://discord.com/channels/904142927389929492/"

  [[params.social]]
  name = "📚"
  url = "https://scholar.google.com/citations?view_op=list_works&hl=en&user=E9mnFzQAAAAJ"

  [[params.social]]
  name = "🆔"
  url = "https://orcid.org/my-orcid?orcid=0000-0001-6443-9897"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[services]
  [services.googleAnalytics]
    ID = 'G-E08ZXTFTTY'
  [services.disqus]
    shortname = 'metafunctor-com'

[outputs]
  home = ["HTML", "JSON"]
